train_key: ../../data/train.csv
test_key: ../../data/test.csv
save_key: ../../data/submissions/baseline.csv

algorithm:
  _target_: src.Model
  emb_pipeline:
    _target_: src.EmbeddingPipeline
    embs:
      - _target_: src.SimilarityEmbedding
